### ISSUE TITLE
Exploratory and Expository Figures

### ISSUE THREAD

**Issue by csetzke6** [csetzke6/Assignment-5#1]
For my exploratory figure, I first created a violin plot of both length and weight for the four different locations of Lake Trout. I then plotted a scatterplot looking at length vs weight in these fish for a second exploratory figure. I noticed one fish had a much, much higher weight compared to the others, so I removed it (I figured this was some sort of typo, but I didn't run a statistical analysis to verify this). I then created an expository figure by adding in colors to each location and making a proper title. This figure used colors that would be accessible to color-blind people. The data were placed in the 'data' directory and the code and figures were placed in the 'figures' directory.

**Comment by mdscheuerell** [comment]
Your figures look great, Chris!
